[Interface]
PrivateKey = AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=
Address = 10.7.0.2/32, fd00:7::2/128
DNS = 10.64.0.1, internal
MTU = 1420
ListenPort = 51820

[Peer]
PublicKey = KCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkc=
PresharedKey = UFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm8=
Endpoint = vpn.example.com:51820
AllowedIPs = 10.64.0.0/24, fd00:64::/64
PersistentKeepalive = 25
